var create = require('ut-error').define;

var Rule = create('rule');
var Generic = create('generic', Rule);
var ExceedMinAmount = create('exceedMinLimitAmount', Rule, 'Transaction amount is below minimum');
var ExceedMaxAmount = create('exceedMaxLimitAmount', Rule, 'Transaction amount is above maximum');
var ExceedDailyLimitAmount = create('exceedDailyLimitAmount', Rule, 'Daily amount limit reached');
var ExceedDailyLimitCount = create('exceedDailyLimitCount', Rule, 'Daily count limit reached');
var ExceedWeeklyLimitAmount = create('exceedWeeklyLimitAmount', Rule, 'Weekly amount limit reached');
var ExceedWeeklyLimitCount = create('exceedWeeklyLimitCount', Rule, 'Weekly count limit reached');
var ExceedMonthlyLimitAmount = create('exceedMonthlyLimitAmount', Rule, 'Monthly amount limit reached');
var ExceedMonthlyLimitCount = create('exceedMonthlyLimitCount', Rule, 'Monthly count limit reached');
var UnauthorizedMinAmount = create('unauthorizedMinLimitAmount', Rule, 'Transaction amount below minimum unauthorized');
var UnauthorizedMaxAmount = create('unauthorizedMaxLimitAmount', Rule, 'Transaction amount above maximum unauthorized');
var UnauthorizedDailyLimitAmount = create('unauthorizedDailyLimitAmount', Rule, 'Daily amount limit unauthorized');
var UnauthorizedDailyLimitCount = create('unauthorizedDailyLimitCount', Rule, 'Daily count limit unauthorized');
var UnauthorizedWeeklyLimitAmount = create('unauthorizedWeeklyLimitAmount', Rule, 'Weekly amount limit unauthorized');
var UnauthorizedWeeklyLimitCount = create('unauthorizedWeeklyLimitCount', Rule, 'Weekly count limit unauthorized');
var UnauthorizedMonthlyLimitAmount = create('unauthorizedMonthlyLimitAmount', Rule, 'Monthly amount limit unauthorized');
var UnauthorizedMonthlyLimitCount = create('unauthorizedMonthlyLimitCount', Rule, 'Monthly count limit unauthorized');
var DuplicatedPriority = create('duplicatedPriority', Rule, 'Rule with this priority already exists');

module.exports = {
    rule: cause => new Rule(cause),
    generic: cause => new Generic(cause),
    exceedMinAmount: cause => new ExceedMinAmount(cause),
    exceedMaxAmount: cause => new ExceedMaxAmount(cause),
    exceedDailyLimitAmount: cause => new ExceedDailyLimitAmount(cause),
    exceedDailyLimitCount: cause => new ExceedDailyLimitCount(cause),
    exceedWeeklyLimitAmount: cause => new ExceedWeeklyLimitAmount(cause),
    exceedWeeklyLimitCount: cause => new ExceedWeeklyLimitCount(cause),
    exceedMonthlyLimitAmount: cause => new ExceedMonthlyLimitAmount(cause),
    exceedMonthlyLimitCount: cause => new ExceedMonthlyLimitCount(cause),
    duplicatedPriority: cause => new DuplicatedPriority(cause),
    unauthorizedMinAmount: cause => new UnauthorizedMinAmount(cause),
    unauthorizedMaxAmount: cause => new UnauthorizedMaxAmount(cause),
    unauthorizedDailyLimitAmount: cause => new UnauthorizedDailyLimitAmount(cause),
    unauthorizedDailyLimitCount: cause => new UnauthorizedDailyLimitCount(cause),
    unauthorizedWeeklyLimitAmount: cause => new UnauthorizedWeeklyLimitAmount(cause),
    unauthorizedWeeklyLimitCount: cause => new UnauthorizedWeeklyLimitCount(cause),
    unauthorizedMonthlyLimitAmount: cause => new UnauthorizedMonthlyLimitAmount(cause),
    unauthorizedMonthlyLimitCount: cause => new UnauthorizedMonthlyLimitCount(cause)
};
