CREATE TABLE [rule].[condition] (
    conditionId INT IDENTITY(1000,1) NOT NULL,
    [priority] INT,
    channelCountryId BIGINT,
    channelRegionId BIGINT,
    channelCityId BIGINT,
    channelOrganizationId BIGINT,
    channelSupervisorId BIGINT,
    channelTag NVARCHAR(255),
    channelRoleId BIGINT,
    channelId BIGINT,
    operationId BIGINT,
    operationTag NVARCHAR(255),
    operationStartDate DATETIME,
    operationEndDate DATETIME,
    sourceCountryId BIGINT,
    sourceRegionId BIGINT,
    sourceCityId BIGINT,
    sourceOrganizationId BIGINT,
    sourceSupervisorId BIGINT,
    sourceTag NVARCHAR(255),
    sourceId BIGINT,
    sourceCardProductId BIGINT,
    sourceAccountProductId BIGINT,
    sourceAccountId BIGINT,
    destinationCountryId BIGINT,
    destinationRegionId BIGINT,
    destinationCityId BIGINT,
    destinationOrganizationId BIGINT,
    destinationSupervisorId BIGINT,
    destinationTag NVARCHAR(255),
    destinationId BIGINT,
    destinationAccountProductId BIGINT,
    destinationAccountId BIGINT,
    CONSTRAINT [pkRuleCondition] PRIMARY KEY CLUSTERED ([conditionId] ASC),
    CONSTRAINT [ukRuleCondtitionPriority] UNIQUE ([priority] ASC)
)